"""add_revoke_filed

Revision ID: 736cae4d4921
Revises: ef7e752d869c
Create Date: 2025-10-03 16:41:44.787478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '736cae4d4921'
down_revision: Union[str, Sequence[str], None] = 'ef7e752d869c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('revoked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'revoked')
    # ### end Alembic commands ###
